main: com.puddingkc.BoomBag
version: 1.0.2
api-version: 1.16
author: "PuddingKC"
description: "受到火焰伤害时，背包内的TNT会在玩家周围点燃"
name: BoomBag
permissions:
  boombag.bypass:
    default: op
    description: 免疫点燃